// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BaseProto.proto

package proto;

public final class BaseProto {
  private BaseProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   * p2p 消息广播到集群 半数以上节点 确认服务down 服务下线
   * </pre>
   *
   * Protobuf enum {@code MessageType}
   */
  public enum MessageType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * 心跳 心跳同步配置 变更
     * </pre>
     *
     * <code>heartBeat = 0;</code>
     */
    heartBeat(0),
    /**
     * <pre>
     * 服务上线
     * </pre>
     *
     * <code>serverOn = 1;</code>
     */
    serverOn(1),
    /**
     * <pre>
     * 服务下线
     * </pre>
     *
     * <code>serverOff = 2;</code>
     */
    serverOff(2),
    /**
     * <pre>
     *客户端上线
     * </pre>
     *
     * <code>clientOn = 3;</code>
     */
    clientOn(3),
    /**
     * <pre>
     *客户端下线
     * </pre>
     *
     * <code>clientOff = 4;</code>
     */
    clientOff(4),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * 心跳 心跳同步配置 变更
     * </pre>
     *
     * <code>heartBeat = 0;</code>
     */
    public static final int heartBeat_VALUE = 0;
    /**
     * <pre>
     * 服务上线
     * </pre>
     *
     * <code>serverOn = 1;</code>
     */
    public static final int serverOn_VALUE = 1;
    /**
     * <pre>
     * 服务下线
     * </pre>
     *
     * <code>serverOff = 2;</code>
     */
    public static final int serverOff_VALUE = 2;
    /**
     * <pre>
     *客户端上线
     * </pre>
     *
     * <code>clientOn = 3;</code>
     */
    public static final int clientOn_VALUE = 3;
    /**
     * <pre>
     *客户端下线
     * </pre>
     *
     * <code>clientOff = 4;</code>
     */
    public static final int clientOff_VALUE = 4;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MessageType valueOf(int value) {
      return forNumber(value);
    }

    public static MessageType forNumber(int value) {
      switch (value) {
        case 0: return heartBeat;
        case 1: return serverOn;
        case 2: return serverOff;
        case 3: return clientOn;
        case 4: return clientOff;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MessageType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
            public MessageType findValueByNumber(int number) {
              return MessageType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return proto.BaseProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final MessageType[] VALUES = values();

    public static MessageType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private MessageType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:MessageType)
  }

  /**
   * Protobuf enum {@code BodyType}
   */
  public enum BodyType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * 新增配置
     * </pre>
     *
     * <code>add = 0;</code>
     */
    add(0),
    /**
     * <pre>
     * 更新配置
     * </pre>
     *
     * <code>update = 1;</code>
     */
    update(1),
    /**
     * <pre>
     * 下线配置
     * </pre>
     *
     * <code>offline = 2;</code>
     */
    offline(2),
    /**
     * <pre>
     * 上线配置
     * </pre>
     *
     * <code>online = 3;</code>
     */
    online(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * 新增配置
     * </pre>
     *
     * <code>add = 0;</code>
     */
    public static final int add_VALUE = 0;
    /**
     * <pre>
     * 更新配置
     * </pre>
     *
     * <code>update = 1;</code>
     */
    public static final int update_VALUE = 1;
    /**
     * <pre>
     * 下线配置
     * </pre>
     *
     * <code>offline = 2;</code>
     */
    public static final int offline_VALUE = 2;
    /**
     * <pre>
     * 上线配置
     * </pre>
     *
     * <code>online = 3;</code>
     */
    public static final int online_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static BodyType valueOf(int value) {
      return forNumber(value);
    }

    public static BodyType forNumber(int value) {
      switch (value) {
        case 0: return add;
        case 1: return update;
        case 2: return offline;
        case 3: return online;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<BodyType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        BodyType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<BodyType>() {
            public BodyType findValueByNumber(int number) {
              return BodyType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return proto.BaseProto.getDescriptor().getEnumTypes().get(1);
    }

    private static final BodyType[] VALUES = values();

    public static BodyType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private BodyType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:BodyType)
  }

  public interface BaseMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:BaseMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 消息id
     * </pre>
     *
     * <code>string messageId = 1;</code>
     */
    java.lang.String getMessageId();
    /**
     * <pre>
     * 消息id
     * </pre>
     *
     * <code>string messageId = 1;</code>
     */
    com.google.protobuf.ByteString
        getMessageIdBytes();

    /**
     * <code>.MessageType MessageType = 2;</code>
     */
    int getMessageTypeValue();
    /**
     * <code>.MessageType MessageType = 2;</code>
     */
    proto.BaseProto.MessageType getMessageType();

    /**
     * <code>.BodyType BodyType = 3;</code>
     */
    int getBodyTypeValue();
    /**
     * <code>.BodyType BodyType = 3;</code>
     */
    proto.BaseProto.BodyType getBodyType();

    /**
     * <code>bytes data = 4;</code>
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code BaseMessage}
   */
  public  static final class BaseMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:BaseMessage)
      BaseMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BaseMessage.newBuilder() to construct.
    private BaseMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BaseMessage() {
      messageId_ = "";
      messageType_ = 0;
      bodyType_ = 0;
      data_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BaseMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              messageId_ = s;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              messageType_ = rawValue;
              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              bodyType_ = rawValue;
              break;
            }
            case 34: {

              data_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.BaseProto.internal_static_BaseMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.BaseProto.internal_static_BaseMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.BaseProto.BaseMessage.class, proto.BaseProto.BaseMessage.Builder.class);
    }

    public static final int MESSAGEID_FIELD_NUMBER = 1;
    private volatile java.lang.Object messageId_;
    /**
     * <pre>
     * 消息id
     * </pre>
     *
     * <code>string messageId = 1;</code>
     */
    public java.lang.String getMessageId() {
      java.lang.Object ref = messageId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        messageId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 消息id
     * </pre>
     *
     * <code>string messageId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMessageIdBytes() {
      java.lang.Object ref = messageId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        messageId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MESSAGETYPE_FIELD_NUMBER = 2;
    private int messageType_;
    /**
     * <code>.MessageType MessageType = 2;</code>
     */
    public int getMessageTypeValue() {
      return messageType_;
    }
    /**
     * <code>.MessageType MessageType = 2;</code>
     */
    public proto.BaseProto.MessageType getMessageType() {
      @SuppressWarnings("deprecation")
      proto.BaseProto.MessageType result = proto.BaseProto.MessageType.valueOf(messageType_);
      return result == null ? proto.BaseProto.MessageType.UNRECOGNIZED : result;
    }

    public static final int BODYTYPE_FIELD_NUMBER = 3;
    private int bodyType_;
    /**
     * <code>.BodyType BodyType = 3;</code>
     */
    public int getBodyTypeValue() {
      return bodyType_;
    }
    /**
     * <code>.BodyType BodyType = 3;</code>
     */
    public proto.BaseProto.BodyType getBodyType() {
      @SuppressWarnings("deprecation")
      proto.BaseProto.BodyType result = proto.BaseProto.BodyType.valueOf(bodyType_);
      return result == null ? proto.BaseProto.BodyType.UNRECOGNIZED : result;
    }

    public static final int DATA_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>bytes data = 4;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getMessageIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, messageId_);
      }
      if (messageType_ != proto.BaseProto.MessageType.heartBeat.getNumber()) {
        output.writeEnum(2, messageType_);
      }
      if (bodyType_ != proto.BaseProto.BodyType.add.getNumber()) {
        output.writeEnum(3, bodyType_);
      }
      if (!data_.isEmpty()) {
        output.writeBytes(4, data_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getMessageIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, messageId_);
      }
      if (messageType_ != proto.BaseProto.MessageType.heartBeat.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, messageType_);
      }
      if (bodyType_ != proto.BaseProto.BodyType.add.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, bodyType_);
      }
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, data_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.BaseProto.BaseMessage)) {
        return super.equals(obj);
      }
      proto.BaseProto.BaseMessage other = (proto.BaseProto.BaseMessage) obj;

      boolean result = true;
      result = result && getMessageId()
          .equals(other.getMessageId());
      result = result && messageType_ == other.messageType_;
      result = result && bodyType_ == other.bodyType_;
      result = result && getData()
          .equals(other.getData());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MESSAGEID_FIELD_NUMBER;
      hash = (53 * hash) + getMessageId().hashCode();
      hash = (37 * hash) + MESSAGETYPE_FIELD_NUMBER;
      hash = (53 * hash) + messageType_;
      hash = (37 * hash) + BODYTYPE_FIELD_NUMBER;
      hash = (53 * hash) + bodyType_;
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.BaseProto.BaseMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.BaseProto.BaseMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.BaseProto.BaseMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.BaseProto.BaseMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.BaseProto.BaseMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.BaseProto.BaseMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.BaseProto.BaseMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.BaseProto.BaseMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.BaseProto.BaseMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.BaseProto.BaseMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.BaseProto.BaseMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.BaseProto.BaseMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.BaseProto.BaseMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BaseMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:BaseMessage)
        proto.BaseProto.BaseMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.BaseProto.internal_static_BaseMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.BaseProto.internal_static_BaseMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.BaseProto.BaseMessage.class, proto.BaseProto.BaseMessage.Builder.class);
      }

      // Construct using proto.BaseProto.BaseMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        messageId_ = "";

        messageType_ = 0;

        bodyType_ = 0;

        data_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.BaseProto.internal_static_BaseMessage_descriptor;
      }

      @java.lang.Override
      public proto.BaseProto.BaseMessage getDefaultInstanceForType() {
        return proto.BaseProto.BaseMessage.getDefaultInstance();
      }

      @java.lang.Override
      public proto.BaseProto.BaseMessage build() {
        proto.BaseProto.BaseMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public proto.BaseProto.BaseMessage buildPartial() {
        proto.BaseProto.BaseMessage result = new proto.BaseProto.BaseMessage(this);
        result.messageId_ = messageId_;
        result.messageType_ = messageType_;
        result.bodyType_ = bodyType_;
        result.data_ = data_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.BaseProto.BaseMessage) {
          return mergeFrom((proto.BaseProto.BaseMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.BaseProto.BaseMessage other) {
        if (other == proto.BaseProto.BaseMessage.getDefaultInstance()) return this;
        if (!other.getMessageId().isEmpty()) {
          messageId_ = other.messageId_;
          onChanged();
        }
        if (other.messageType_ != 0) {
          setMessageTypeValue(other.getMessageTypeValue());
        }
        if (other.bodyType_ != 0) {
          setBodyTypeValue(other.getBodyTypeValue());
        }
        if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.BaseProto.BaseMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.BaseProto.BaseMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object messageId_ = "";
      /**
       * <pre>
       * 消息id
       * </pre>
       *
       * <code>string messageId = 1;</code>
       */
      public java.lang.String getMessageId() {
        java.lang.Object ref = messageId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          messageId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 消息id
       * </pre>
       *
       * <code>string messageId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMessageIdBytes() {
        java.lang.Object ref = messageId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          messageId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 消息id
       * </pre>
       *
       * <code>string messageId = 1;</code>
       */
      public Builder setMessageId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        messageId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息id
       * </pre>
       *
       * <code>string messageId = 1;</code>
       */
      public Builder clearMessageId() {
        
        messageId_ = getDefaultInstance().getMessageId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息id
       * </pre>
       *
       * <code>string messageId = 1;</code>
       */
      public Builder setMessageIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        messageId_ = value;
        onChanged();
        return this;
      }

      private int messageType_ = 0;
      /**
       * <code>.MessageType MessageType = 2;</code>
       */
      public int getMessageTypeValue() {
        return messageType_;
      }
      /**
       * <code>.MessageType MessageType = 2;</code>
       */
      public Builder setMessageTypeValue(int value) {
        messageType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.MessageType MessageType = 2;</code>
       */
      public proto.BaseProto.MessageType getMessageType() {
        @SuppressWarnings("deprecation")
        proto.BaseProto.MessageType result = proto.BaseProto.MessageType.valueOf(messageType_);
        return result == null ? proto.BaseProto.MessageType.UNRECOGNIZED : result;
      }
      /**
       * <code>.MessageType MessageType = 2;</code>
       */
      public Builder setMessageType(proto.BaseProto.MessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        messageType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.MessageType MessageType = 2;</code>
       */
      public Builder clearMessageType() {
        
        messageType_ = 0;
        onChanged();
        return this;
      }

      private int bodyType_ = 0;
      /**
       * <code>.BodyType BodyType = 3;</code>
       */
      public int getBodyTypeValue() {
        return bodyType_;
      }
      /**
       * <code>.BodyType BodyType = 3;</code>
       */
      public Builder setBodyTypeValue(int value) {
        bodyType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.BodyType BodyType = 3;</code>
       */
      public proto.BaseProto.BodyType getBodyType() {
        @SuppressWarnings("deprecation")
        proto.BaseProto.BodyType result = proto.BaseProto.BodyType.valueOf(bodyType_);
        return result == null ? proto.BaseProto.BodyType.UNRECOGNIZED : result;
      }
      /**
       * <code>.BodyType BodyType = 3;</code>
       */
      public Builder setBodyType(proto.BaseProto.BodyType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        bodyType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.BodyType BodyType = 3;</code>
       */
      public Builder clearBodyType() {
        
        bodyType_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes data = 4;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>bytes data = 4;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes data = 4;</code>
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:BaseMessage)
    }

    // @@protoc_insertion_point(class_scope:BaseMessage)
    private static final proto.BaseProto.BaseMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.BaseProto.BaseMessage();
    }

    public static proto.BaseProto.BaseMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BaseMessage>
        PARSER = new com.google.protobuf.AbstractParser<BaseMessage>() {
      @java.lang.Override
      public BaseMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BaseMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BaseMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BaseMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public proto.BaseProto.BaseMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BaseMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BaseMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017BaseProto.proto\032\031google/protobuf/any.p" +
      "roto\"n\n\013BaseMessage\022\021\n\tmessageId\030\001 \001(\t\022!" +
      "\n\013MessageType\030\002 \001(\0162\014.MessageType\022\033\n\010Bod" +
      "yType\030\003 \001(\0162\t.BodyType\022\014\n\004data\030\004 \001(\014*V\n\013" +
      "MessageType\022\r\n\theartBeat\020\000\022\014\n\010serverOn\020\001" +
      "\022\r\n\tserverOff\020\002\022\014\n\010clientOn\020\003\022\r\n\tclientO" +
      "ff\020\004*8\n\010BodyType\022\007\n\003add\020\000\022\n\n\006update\020\001\022\013\n" +
      "\007offline\020\002\022\n\n\006online\020\003B\007\n\005protob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        }, assigner);
    internal_static_BaseMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_BaseMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BaseMessage_descriptor,
        new java.lang.String[] { "MessageId", "MessageType", "BodyType", "Data", });
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
